### ISSUE TITLE
requirements and python version

### ISSUE THREAD

**Issue by halfguru** [AstroCoding/btd6_autoplay#3]
1. Add a requirements.txt for  #dependencies
2. Update readme with python 3.8 because of assignment expression:

> while (key := input('Press 1 for startUp, and 2 for darkCastle\n------------------\n>>>')):

**Comment by AstroCoding** [comment]
The := operator is available in Python 3.7 as far as I'm aware but I will specify in the ReadMe. As for dependences in a seperate file, I will do it eventually, but it isn't in my list of must haves at the moment because we are currently working on expanding the script to make it easier for users to build their own level loops.

**Comment by halfguru** [comment]
I couldn't run it on python 3.7.0. The "walrus operator" has been implemented in 3.8 according to this changelog https://docs.python.org/3/whatsnew/3.8.html

**Comment by AstroCoding** [comment]
Alright, we have updated the ReadMe to specify and have created a requirements.txt for the 2 extensions. We will be uploading it shortly, but we're still working on the refactoring which makes user map creation a bit easier.

**Comment by BowserV2** [comment]
Changes have been made in latest push [here](https://github.com/AstroCoding/btd6_autoplay/commit/0420cffb6b71176eda943e728f1f2846de06947b)
